## LEVEL 1: Basic Business Understanding
 
USE zepto_sql;

 =======================

--- 1.  How many customers are registered on the platform?
 =======================

   SELECT COUNT(*) AS total_customers
   FROM orders;

================

---- 2.  How many total orders have been placed?
   ==============

 SELECT COUNT(*) AS total_orders
 FROM orders;

==============
---- 3. How many orders are delivered, cancelled, and pending?
================

SELECT order_status , COUNT(*) AS total_count
FROM orders
GROUP BY order_status;
=====================

---- 4. What are the distinct cities customers belong to?
================
 SELECT DISTINCT city 
  FROM customers;

=======================

---- 5.. What is the average age of customers?
===============  
  
   SELECT ROUND(AVG(age) , 2) AS avg_customer_age
    FROM customers;
======================

--- 6.  What is the earliest and latest order date?

====================

 SELECT MIN(order_date) AS first_order_date,

 SELECT MAX(order_date) AS last_order_date

 FROM orders;

===============

--- 7.. What is the total revenue generated?

=============

SELECT SUM(amount) as total_revenue
FROM transaction;

=================

---- 8.How many orders were placed after a specific date?

======================

 SELECT 
   
COUNT(*) AS order_after_2024-02-01
FROM orders
WHERE order_date > '2024-02-01';

==============
---- 9 ..How many unique customers placed orders?

   SELECT (DISTINCT customer_id) AS active_customers
FROM orders;

================
---- 10... What payment modes are used on the platform?
 
SELECT  DISTINCT payment_mode
 FROM transaction;
   

# LEVEL 2 ---

--1.Which customers placed which orders?
===========================

 SELECT 
  c.customer_id ,
  c.customer_name,
  o.order_status,
  o.order_date
  
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id;

=================================

--- 2.. What is the delivery status of each order?

SELECT 
  o.order_id ,
  o.order_date,
  o.order_status,
  d.delivery_status,
  d.distance_km
FROM orders o 
JOIN delivery d
ON o.order_id = d.order_id;

========================

-- 3. What is the transaction amount for each order?

==============================
 SELECT
   o.order_id,
   o.customer_id,
   t.amount,
   t.payment_mode,
    o.order_date
FROM orders o
JOIN transactions t
ON o.order_id = t.order_id;

===============================

--4.. Which customers have placed more than one order?
Identifies repeat customers.
=========================
SELECT 
    user_id,
    COUNT(order_id) AS total_orders
FROM orders
GROUP BY user_id
HAVING COUNT(order_id) > 1;




-- 5. Which delivered orders have no ratings?
===========================

SELECT 
    o.order_id,
    o.customer_id,
    o.order_date
FROM orders o
LEFT JOIN ratings r
    ON o.order_id = r.order_id
WHERE r.rating_id IS NULL;

==============================

--6.Show customer, order, and payment details together.
========================

SELECT 
o.order_id,
c.customer_name,
c.city,
o.order_date,
t.amount,
t.payment_mode
FROM orders o
JOIN customers c
   ON o.customer_id = c.customer_id
JOIN transactions t
   ON o.order_id = t.order_id;
================================


--- 7. What is the delivery distance for delivered orders
 =====================
     
SELECT 
  delivery_id,
  order_id,
  distance_km
  FROM delivery
  WHERE delivery_status = 'Delivered';
======================================


--- 8 . Which customers placed the highest number of delivered orders?
===================================

   SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS delivered_orders
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
WHERE o.order_status = 'Delivered'
GROUP BY c.customer_id, c.customer_name
ORDER BY delivered_orders DESC;


==================================

-- 9.Which orders were paid using UPI, Card, or Cash?

=============================

SELECT 
 o.order_id ,
 t.payment_mode
FROM transactions t
JOIN orders o
WHERE t.payment_mode IN('UPI','Card','Cash');

==========================

--10..  Which customers have never given a rating?

 ====================================

SELECT  
  c.customer_id,
  c.customer_name
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
LEFT JOIN ratings r
   ON o.order_id = r.order_id 
WHERE r.rating_id IS NULL;

========================================

--- Business Aggregation & KPIs

============================
---1 ..What is the total revenue generated by each customer?

======================================

  SELECT 
 c.customer_name ,
 c.customer_id,
 sum(t.amount) as total_amount
 FROM customers c
 JOIN orders o
 ON c.customer_id = o.customer_id
 JOIN transactions t
 ON t.order_id = o.order_id
 GROUP BY c.customer_name , c.customer_id;
 
=========================================
 -- 2..Who are the top 5 customers by revenue?
    
  SELECT 
  o.order_id,
  c.customer_name,
  c.age,
  c.city,
  SUM(t.amount) as total_amount
  FROM customers c
  JOIN orders o
  ON c.customer_id = o.customer_id
  JOIN transactions t
  ON t.order_id = o.order_id 
  GROUP BY o.order_id , c.customer_name 
  ORDER BY total_amount DESC
  LIMIT 5;

========================================

---3. What is the average order value (AOV)?

=====================================
  
SELECT 
   AVG(order_total) as avg_order_value
FROM (
   
    SELECT 
      order_id,
      SUM(amount) as order_total
      FROM transactions 
      GROUP BY order_id ) t;
=========================================

--4. How many orders are placed from each city?

=======================================


SELECT c.city,
count(o.order_id) as total_orders
from orders o
JOIN customers c
ON c.customer_id = o.customer_id
GROUP BY city;

=============================
---5..  What is the average delivery distance?
===============================

select 
   ROUND(AVG(distance_km) , 2) as avg_distance_km 
    FROM delivery;
=======================================
---6.How many long-distance deliveries (>3 km) occur
======================================
SELECT 
    delivery_id,
    distance_km ,
    delivery_status
    FROM delivery 
    WHERE distance_km > 3;

=====================================
--7.What is the order fulfilment rate?
============================================

 SELECT 
   ROUND(
   SUM(CASE WHEN order_status = 'Delivered' THEN 1 ELSE 0
   END)*100.0/COUNT(*),2)
   AS fulfilment_rate_percentage
   from orders;
=======================================
---8. What percentage of orders are cancelled?
======================================
  SELECT 
   ROUND(
   SUM(CASE WHEN order_status = 'Cancelled' THEN 1 ELSE 0
   END)*100.0/COUNT(*),2)
   AS cancelled_order_percentage
   from orders;

===========================================
---9.. Which payment mode generates the highest revenue ?
===========================
  SELECT payment_mode,
       SUM(amount) as total_amount
FROM transactions
group by payment_mode
ORDER BY total_amount DESC;
   
========================================


























































































































